### PR TITLE
👷 Add production build

### PR DESCRIPTION
**Pull request by Dev-dfm**
Build guides  
https://vitejs.dev/guide/build.html  
https://storybook.js.org/docs/react/workflows/publish-storybook#build-storybook-as-a-static-web-application  
https://expressjs.com/en/starter/static-files.html

### CODE REVIEW

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by J-Bannach — APPROVED** [review]
lgtm 💯

**Review by jujuzitroni — APPROVED** [review]
lgtm 🚀

**Review by daebert — APPROVED** [review]
lgtm!

**Pull request merged**
